baseURL = "https://blogdojoao-nu.vercel.app/"
languageCode = "pt-br"
title = "Blog do João"
theme = "github-style"

[params]
author = "João Pedro Della Guardia"
description = "Bioinformata."
github = "jpdellaguardia"
twitter = "jpguardia_"
linkedin = "joaopedrodellaguardia"
instagram = "jpguardia_"
email = "joaoemberlin@gmail.com"
url = "joaoemberlin.com"
keywords = "blog, bioinformática"
rss = true
lastmod = true
userStatusEmoji = "🧬"
favicon = "/images/github-mark.png"
avatar = "https://github.com/jpdellaguardia.png"
headerIcon = "/images/github-mark-white.png"
location = "Berlim, Alemanha"
enableGitalk = false

[permalinks]
post = "/post/:slug/"

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
